export const SET_DRAWER_VISIBILITY_ACTION = 'SET_DRAWER_VISIBILITY_ACTION';
export const SET_SELECTED_OPERATOR = 'SET_SELECTED_OPERATOR';
export const DELETE_SELECTED_OPERATOR = 'DELETE_SELECTED_OPERATOR';
export const RESET_SELECTED_FILTERS = 'RESET_SELECTED_FILTERS';
